PMT/Models/Comment.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;

namespace PMT.Models
{
    public class Comment
    {
        public Comment()
        {
            // Likes = new HashSet<Like>();
        }
        [Key]
        public int CommentId { get; set; }

        public string Message { get; set; }
        public int ObituaryId { get; set; }
        public string PostBy { get; set; }
        public int UserProfile_UserId { get; set; }
        public int LikeCount { get; set; }
        
        [ForeignKey("ObituaryId")]
        public virtual Obituary Obituary { get; set; }

        public virtual ICollection<Like> Likes { get; set; }
    }

    //public class CommentModel
    //{
    //    public int CommentId { get; set; }

    //    public string Message { get; set; }
    //    public int ObituaryId { get; set; }
    //    public string PostBy{get;set;}
    //    public int UserProfile_UserId { get; set; }
    //    [ForeignKey("ObituaryId")]
    //    public virtual Obituary Obituary { get; set; }

    //}
}

PMT/Controllers/CommentController.cs
using PMT.Filters;
using PMT.Helper;
using PMT.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebMatrix.WebData;

namespace PMT.Controllers
{
    [InitializeSimpleMembership]
    public class CommentController : Controller
    {
        //
        // GET: /Comment/
        private PMTContext db = new PMTContext();
        public ActionResult Index()
        {
            return View();
        }
        [Authorize]
        public ActionResult Create()
        {

            return View();

        }

        //public ActionResult comments()
        //{
        //    ViewBag.PostId = 1;
        //    ViewBag.UserId = 1;
        //    return View("Create");
        //}

        // POST: /Post/Create

        //[HttpPost]
        //public ActionResult comments()
        //{

        //    return View("Create");
        //}
        [HttpPost]
        [Authorize]
        public ActionResult Create(Comment comment, string classification)
        {
            //var loggedUser=HttpContext.Session["UserData"] as LoggedUser;

            //  comment.UserProfile_UserId = loggedUser.UserId;

            var post = db.Obituary.Where(o => o.ObituaryId == comment.ObituaryId).SingleOrDefault();

            if (post != null)
            {
                comment.UserProfile_UserId = (int)WebSecurity.CurrentUserId;
                comment.PostBy = WebSecurity.CurrentUserName;

                db.Comments.Add(comment);
                db.SaveChanges();

            }




            //var query = db.UserProfiles.Where(up => up.UserId == comment.UserProfile_UserId).First();
            //ViewBag.UserName = query.UserName;
            var dataList = db.Comments.Where(c => c.CommentId == comment.CommentId).ToList();
            //List<CommentModel> newList = new List<CommentModel>();
            //foreach (var item in dataList) {
            //    CommentModel model = new CommentModel();
            //    model.Message = item.Message;
            //    model.PostBy = query.UserName;
            //    newList.Add(model);
            //}
            //  return Json(comment, JsonRequestBehavior.AllowGet);









            return Json(new { PartialView = MvcHelper.RenderPartialView(this, "_Index", dataList, null) });

        }

        // GET: /Post/Edit/5
        [HttpGet]
        public ActionResult Edit(int id = 0)
        {
            Comment comment = db.Comments.Find(id);

            if (comment == null)
            {
                return HttpNotFound();
            }
            return Json(new { PartialView = MvcHelper.RenderPartialView(this, "_Edit", comment, null) }, JsonRequestBehavior.AllowGet);
        }

        //
        // POST: /Post/Edit/5

        [HttpPost]
        public ActionResult Edit(Comment comment)
        {
            //if (ModelState.IsValid)
            //{
            Comment editComment = db.Comments.Where(c => c.CommentId == comment.CommentId).SingleOrDefault();
            editComment.Message = comment.Message;
            db.Entry(editComment).State = EntityState.Modified;
            db.SaveChanges();

            //return RedirectToAction("Obituary_List", "Post", new { area = "" });
            //}

            return Json(new { comment = comment.Message });
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }


        //
        // GET: /Post/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Comment comment = db.Comments.Find(id);
            if (comment == null)
            {
                return HttpNotFound();
            }
            return View(comment);
        }

        //
        // POST: /Post/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Comment comment = db.Comments.Find(id);
            if (comment != null)
            {
                db.Comments.Remove(comment);
                db.SaveChanges();
                return Json(comment, JsonRequestBehavior.AllowGet);
            }
            return Json(db.Comments.Count(), JsonRequestBehavior.AllowGet);
        }


        [HttpGet]

        public ActionResult GetCommentCount(Obituary obituary)
        {
            var comm = db.Comments.Where(c => c.ObituaryId == obituary.ObituaryId).ToList().Count();

            return Json(comm);
        }





        [HttpPost]
        public ActionResult Like(Comment comment)
        {
            //like.Comments = db.Comments.Find(comment.CommentId);

            var loggedinUser = WebSecurity.CurrentUserId;

            var like = db.Likes.Where(l => l.CommentId == comment.CommentId && l.UserProfile_UserId == loggedinUser).SingleOrDefault();

            var commentLike = db.Comments.Where(c => c.CommentId == comment.CommentId).SingleOrDefault();

            if (like == null)
            {
                Like likes = new Like();
                likes.CommentId = comment.CommentId;
                likes.UserProfile_UserId = loggedinUser;
                if (commentLike != null)
                {
                    commentLike.LikeCount += 1;
                }
                db.Likes.Add(likes);
                db.SaveChanges();
            }

            //var userlike = db.Likes.Where(l => l.UserProfile_UserId == WebSecurity.CurrentUserId && l.CommentId == comment.CommentId);

            //db.CommentLikes.Add(like);
            //db.SaveChanges();
            //var likes = db.CommentLikes.Count();
            return Json(new { commentLike = commentLike.LikeCount }, JsonRequestBehavior.AllowGet);
        }












    }
}

PMT/Controllers/PostController.cs
using PMT.Filters;
using PMT.Models;
using PMT.Utility;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebMatrix.WebData;

namespace PMT.Controllers
{
    [InitializeSimpleMembership]
    public class PostController : AppController
    {
        private PMTContext db = new PMTContext();

        //
        // GET: /Post/
        [HttpGet]

        public ActionResult Details(int id = 0)
        {
            Obituary obituary = db.Obituary.Find(id);
            if (obituary == null)
            {
                return HttpNotFound();
            }

            //ViewBag.comment = co;
            return View(obituary);
        }

        //
        // GET: /Post/Create
        [Authorize]
        public ActionResult Create()
        {

            List<SelectListItem> li = new List<SelectListItem>();
            li.Add(new SelectListItem { Text = "Obituary", Value = "Obituary" });
            li.Add(new SelectListItem { Text = "Tribute", Value = "Tribute" });
            ViewBag.classifications = li;
            

            List<SelectListItem> lis = new List<SelectListItem>();
            lis.Add(new SelectListItem { Text = "Select", Value = "" });
            lis.Add(new SelectListItem { Text = "Adult", Value = "Adult" });
            lis.Add(new SelectListItem { Text = "Child", Value = "Child" });
           
            ViewData["ObituaryCategory"] = lis;

            return View();
        }

        //
        // POST: /Post/Create






        public ActionResult Obituary_List(string message)
        {
            if (!string.IsNullOrEmpty(message))
            {
                ViewBag.message = message;
            }
            var obituaries = db.Obituary.Where(x => x.Classifications=="Obituary");
            return View(obituaries);
        }


        public ActionResult Tribute_List(string message)
        {
            if (!string.IsNullOrEmpty(message))
            {
                ViewBag.message = message;
            }
            var tributes = db.Obituary.Where(x => x.Classifications == "Tribute");
            return View(tributes.ToList());
        }



        [HttpGet]
        public ActionResult Obituaries_Next(int lastObituary)   
        {
            List<Obituary> Obituaries = db.Obituary.OrderByDescending(a => a.ObituaryId).ToList();
            int last = 0;
            if (lastObituary == -1)
            {
                Obituaries = Obituaries.Take(6).ToList();
            }
            else if (lastObituary > 0)
            {
                Obituary obituaries = new Obituary();
                obituaries = Obituaries.Where(d => d.ObituaryId == lastObituary).SingleOrDefault();
                if (obituaries != null)
                {
                    int p = Obituaries.IndexOf(obituaries);
                    Obituaries = Obituaries.Skip(p + 1).Take(5).ToList();
                }
            }
            else if (lastObituary == 0)
            {
                Obituaries = null;
            }
            if (Obituaries.Count > 0 && Obituaries != null)
            {
                int len = Obituaries.Count;
                last = Obituaries.ElementAt(len - 1).ObituaryId;
            }

            ViewBag.Obituaries = Obituaries;
            ViewBag.lastObituary = last;
            return PartialView("_Obituary_List");
        }






        [HttpPost]
        public ActionResult Create(Obituary obituary, HttpPostedFileBase imageFile)
        {
            obituary.UserId = (int)WebSecurity.CurrentUserId;
            
                List<SelectListItem> li = new List<SelectListItem>();
                li.Add(new SelectListItem { Text = "Obituary", Value = "Obituary" });
                li.Add(new SelectListItem { Text = "Tribute", Value = "Tribute" });
                ViewBag.classifications = li;


                List<SelectListItem> lis = new List<SelectListItem>();
                lis.Add(new SelectListItem { Text = "Select", Value = "" });
                lis.Add(new SelectListItem { Text = "Adult", Value = "Adult" });
                lis.Add(new SelectListItem { Text = "Child", Value = "Child" });

                ViewData["ObituaryCategory"] = lis;

                var imageName = "";

                imageName = imageFile.FileName;
                var httpPostedFile = Request.Files[0];
                if (httpPostedFile != null)
                {
                    var uploadFilesDir = System.Web.HttpContext.Current.Server.MapPath("~/Images/obituary");
                    if (!Directory.Exists(uploadFilesDir))
                    {
                        Directory.CreateDirectory(uploadFilesDir);
                    }
                    var fileSavePath = Path.Combine(uploadFilesDir, httpPostedFile.FileName);

                    httpPostedFile.SaveAs(fileSavePath);
                    obituary.FileName = imageName;
                }

                if (ModelState.IsValid)
                {
                    
                    db.Obituary.Add(obituary);
                    db.SaveChanges();
                    return RedirectToAction("Index", "Home", new { message = obituary.Classifications + " " + "Added Successfully" });

                    ViewBag.UserId = new SelectList(db.UserProfiles, "UserId", "UserName", obituary.UserId);
                }
            return View(obituary);
        }
            
        //
        // GET: /Post/Edit/5
    [Authorize]
        public ActionResult Edit(int id = 0)
        {


            List<SelectListItem> li = new List<SelectListItem>();
            li.Add(new SelectListItem { Text = "Obituary", Value = "Obituary" });
            li.Add(new SelectListItem { Text = "Tribute", Value = "Tribute" });

            ViewBag.classifications = li;
           


            List<SelectListItem> lis = new List<SelectListItem>();
            lis.Add(new SelectListItem { Text = "Select", Value = "" });
            lis.Add(new SelectListItem { Text = "Adult", Value = "Adult" });
            lis.Add(new SelectListItem { Text = "Child", Value = "Child" });
            ViewData["ObituaryCategory"] = lis;


            Obituary obituary = db.Obituary.Find(id);
            if (obituary == null)
            {
                return HttpNotFound();
            }

            return View(obituary);
        }

        //
        // POST: /Post/Edit/5

  [HttpPost]
        public ActionResult Edit(Obituary obituary, HttpPostedFileBase imageFile)
        {

            obituary.UserId = (int)WebSecurity.CurrentUserId;

            if (ModelState.IsValid)
            {


                var imageName = "";
                if (imageFile != null)
                {
                    imageName = imageFile.FileName;
                    var httpPostedFile = Request.Files[0];
                    if (httpPostedFile != null)
                    {
                        var uploadFilesDir = System.Web.HttpContext.Current.Server.MapPath("~/Images/obituary");
                        if (!Directory.Exists(uploadFilesDir))
                        {
                            Directory.CreateDirectory(uploadFilesDir);
                        }
                        var fileSavePath = Path.Combine(uploadFilesDir, httpPostedFile.FileName);

                        httpPostedFile.SaveAs(fileSavePath);
                        obituary.FileName = imageName;
                    }
                }
                //db.Entry(obituary).State = EntityState.Modified;
                var currentPost=db.Obituary.Find(obituary.ObituaryId);

                db.Entry(currentPost).CurrentValues.SetValues(obituary);
                db.SaveChanges();
                if(obituary.Classifications=="Obituary")
                {
                    return RedirectToAction("Obituary_List", new { message = obituary.Classifications + " " + "Updated Successfully" });
                }
                else if (obituary.Classifications == "Tribute")
                {
                    return RedirectToAction("Tribute_List", new { message = obituary.Classifications + " " + "Updated Successfully" });
                }
                
            }
            ViewBag.UserId = new SelectList(db.UserProfiles, "UserId", "UserName", obituary.UserId);
            return View(obituary);
        }

        //
        // GET: /Post/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Obituary obituary = db.Obituary.Find(id);
            if (obituary == null)
            {
                return HttpNotFound();
            }
            return View(obituary);
        }

        //
        // POST: /Post/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Obituary obituary = db.Obituary.Find(id);
            db.Obituary.Remove(obituary);
            db.SaveChanges();
            return RedirectToAction("Obituary_List");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

PMT/Views/Comment/Create.cshtml
@model PMT.Models.Comment

@{
    ViewBag.Title = "Create";
}



<div class="container">
    <h3 class="center-align">Create</h3>
    @using (Html.BeginForm())
    {
    @Html.ValidationSummary(true)
  
         <input type="hidden" name="ObituaryId" id="ObituaryId" value=" @ViewBag.PostId" />
    
        <div class="input-field col s12">
               <textarea id="Message" name="Message" class="materialize-textarea"></textarea>
            <label for="Message">Message</label>
        </div>
         <div>
            <input type="submit" value="Create"  class="btn btn-green white-text "/>
        </div>
}
    
</div>

PMT/Views/Comment/Delete.cshtml
@model PMT.Models.Comment

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>
<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>Comment</legend>
    <div class="display-label">
         @Html.DisplayNameFor(model => model.Message)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Message)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index","Post")
    </p>
}@*  *@

PMT/Views/Comment/Edit.cshtml
@model PMT.Models.Comment

@{
    ViewBag.Title = "Edit";
}

<h3 class="center-align">Edit</h3>

<div class="col s12">
    @using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <div class="card">
        

        @Html.HiddenFor(model => model.ObituaryId)
        @Html.HiddenFor(model => model.CommentId)

         
         <input type="hidden" name="ObituaryId" id="ObituaryId" value=" @ViewBag.PostId" />
    <div class="row">
        <div class="input-field col s12">
               @*<textarea id="Message" name="Message" class="materialize-textarea" value="@Model.Message"></textarea>
            <label for="Message">Message</label>*@

            @Html.TextAreaFor(model => model.Message, htmlAttributes: new { @class="materialize-textarea"})
        </div>
         <div>
            <input type="submit" value="Update"  class="btn btn-green white-text right"/>
        </div>
    </div>
    </div>
}
</div>

PMT/Views/Comment/_Create.cshtml
<div class="container" >
    <h3 class="center-align">Create Comment</h3>
    @using (Html.BeginForm(null, null, FormMethod.Post, new { id = "CommentForm" }))
    {
    @Html.ValidationSummary(true)
    
         <input type="hidden" id="commentPostId" name="ObituaryId" value=""/>
        @*<input type="hidden" id="commentUserId" name="UserProfile_UserId" value="@ViewBag.currentUserId "/>*@
    
        <div class="input-field col s12">
               <textarea id="Message1" name="Message" class="materialize-textarea"></textarea>
            <label for="Message">Message</label>
        </div>
         <div class="row" id="hidebutton">
            <input value="Create" id="createComment" class="btn btn-green white-text addcom"/>
             <span class="btn btn-green white-text" id="cancelComment">Cancel</span>
        </div>
}
    
</div>

<script>
    $(".addcom").on('click', function () {
        $("#hidebutton").hide();
    })
    $("#cancelComment").on('click', function () {
        $("#Message1").val("");
        $("#hidebutton").hide();
    })
    $("#Message1").focus(function () {
        $("#hidebutton").show();
    })
</script>

PMT/Views/Comment/_Edit.cshtml
@model PMT.Models.Comment



<div class="container">
<div class="col s12">
    @using (Html.BeginForm(null, null, FormMethod.Post, new { @class = "EditCommentForm"+@Model.CommentId }))
    {
    @Html.ValidationSummary(true)

        @Html.HiddenFor(model => model.ObituaryId)
        @Html.HiddenFor(model => model.CommentId)

         
        @* <input type="hidden" name="ObituaryId" id="ObituaryId" value=" @ViewBag.PostId" />*@
    <div class="row">
        <div class="input-field col s12">
               @*<textarea id="Message" name="Message" class="materialize-textarea" value="@Model.Message"></textarea>
            <label for="Message">Message</label>*@

            @Html.TextAreaFor(model => model.Message, htmlAttributes: new { @class="materialize-textarea"})
        </div>
         <div class="input-field col s12">
            <input type="button" value="Cancel" data-comId="@Model.CommentId" id="cncelcomm" class="btn btn-green white-text right"/>   
            <input type="button" value="Update"  data-comId="@Model.CommentId" class="btn btn-green white-text right updateComment"/> &nbsp;
        </div>
    </div>
  
}
    </div>
      </div>

PMT/Views/Comment/_Index.cshtml
@model IEnumerable<PMT.Models.Comment>

@{
}

<div>
   @foreach (var item1 in Model)
   {
   <table class="highlight">
       <tbody>
           <tr id="delcom_@item1.CommentId">
               <td>

                   <span class="@item1.CommentId">@Html.DisplayFor(m => item1.Message)</span>

                   <p class="likeComment" data-commId="@item1.CommentId">
                       <span class="like_@item1.CommentId">@item1.LikeCount</span>
                       <i class="material-icons green-text" style="font-size: 15px;cursor:pointer">thumb_up</i>
                   </p>
                   <span style="display: inline; font-size: 12px;">Posted By: @item1.PostBy</span>
                   <div id="@item1.CommentId"></div>

               </td>

               <td style="display: inline; float: right;">
                   <a data-commentid="@item1.CommentId" class="edit indigo-text" style="cursor:pointer">Edit</a> |  
            @*@Html.ActionLink("Delete", "Delete", "Comment", new { id = item1.CommentId }, htmlAttributes: new { @class="delete red-text"})*@
                   <a data-deletecommentid="@item1.CommentId" class="delete red-text" style="cursor:pointer">Delete</a>
                   @*  <button data-commentid="@item1.CommentId" class="edit indigo-text">Edit</button>   *@

               </td>
               @*@Html.ActionLink("Add Obituary", "Create", "Post", null, new Dictionary<string, Object> { { "class", "waves-effect waves-light btn tooltipped btnclr" }, { "data-tooltip", "Add an Obituary" }, { "id", "newbtn" } })*@
           </tr>
       </tbody>
   </table>

   }


</div>
<script>
    $(document).on('click', '.edit', function () {
        var commId = $(this).attr("data-commentid");
        $.ajax({
            url: "/Comment/Edit",
            type: 'GET',
            data: { id: commId },
            success: function (data) {
                $("#"+commId).append(data.PartialView);
            }
        })
    })

    $(document).on('click', '#cncelcomm', function () {
        var commId = $(this).attr("data-comId");
        $("#"+commId).html("");
       
    })
    $(document).on('click', '.updateComment', function () {
        var commId = $(this).attr("data-comId");
        var form = $(".EditCommentForm"+commId).serialize();
        $.ajax({
            url: "/Comment/Edit",
            type: 'POST',
            data: form,
            success: function (data) {
                $("." + commId).text(data.comment);
                $("#" + commId).html("");
            }
        })

    })


    $(document).on('click', '.likeComment', function () {
        var commId = $(this).attr("data-commId");
        $.ajax({
            url: "/Comment/Like",
            type: 'POST',
            data: {commentId : commId},
            success: function (data) {
                $(".like_" + commId).text(data.commentLike);
            }
        })

    })
   

        $(document).off('click', '.delete').on('click', '.delete', function (e) {
        var commId = $(this).attr("data-deletecommentid");
        $.ajax({
            url: "/Comment/Delete",
            type: 'POST',
            data: { id: commId },
            success: function (data) {
                $("#delcom_" + commId).html('');
                var count = $("#PostCommCount").text();
                count = parseInt(count) - 1;

                $("#PostCommCount").text(count);
                $("#PostCommCount").val(count);
            }
        })

    })












</script>