PMT/Models/Events.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace PMT.Models
{
    public class Events
    {

        public Events() { }
        [Key]
        public int EventId { get; set; }
        public string EventName { get; set; }
        [Required]
        public string EventDate { get; set; }
        public string EventInfo { get; set; }
        [Required]
        public string EventVenue { get; set; }
        [Required]
        public string EventStartTime { get; set; }
        public string EventEndTime { get; set; }
        public string ApprximateDuration { get; set; }
        public int UserProfile_UserId { get; set; }
        public int ObituaryId { get; set; }
        //public int UserId { get; set; }
         [ForeignKey("ObituaryId")]
        public virtual Obituary Obituary { get; set; }

    }
}

PMT/Controllers/EventController.cs
using PMT.Helper;
using PMT.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;
using WebMatrix.WebData;

namespace PMT.Controllers
{
    public class EventController : Controller
    {
        //
        // GET: /Event/
        private PMTContext db = new PMTContext();
        public ActionResult Index()
        {
            return View();
        }
       [Authorize]
        public ActionResult Create(int postId)
        {

            ViewBag.PostId = postId;

            return View();
        }


        //public ActionResult Events()
        //{

        //    return View("Create");
        //}

        //  
        // POST: /Post/Create

        [HttpPost]
       public ActionResult Create(Events events)
        {
          //  events.ObituaryId = postId;
            var post = db.Obituary.Where(o => o.ObituaryId == events.ObituaryId).SingleOrDefault();
            if (ModelState.IsValid)
            {
                if (post != null)
                {
                    db.Events.Add(events);
                    db.SaveChanges();



                }
            }
            var datalist = db.Events.Where(c => c.EventId == events.EventId).ToList();
                
                //return RedirectToAction("Index", "Post", new { area = "" 
            //string erroreventVenue = "";
            //if (events.EventVenue == null)
            //{
            //    erroreventVenue = " error message!";
            //}
            return Json(new { PartialView = MvcHelper.RenderPartialView(this, "_Index", datalist, null) });
          

           
        }

        public ActionResult Edit(int id = 0)
        {
            Events events = db.Events.Find(id);
            if (events == null)
            {
                return HttpNotFound();
            }
            
            return Json(new { PartialView = MvcHelper.RenderPartialView(this, "_Edit", events, null) }, JsonRequestBehavior.AllowGet);
        }

        //
        // POST: /Post/Edit/5

        [HttpPost]
        public ActionResult Edit(Events events)
        {
           //Events evnt=db.Events.Where(e => e.EventId == events.EventId).SingleOrDefault();
           //if (evnt != null)
           //{
           //    events.Obituary.UserId = evnt.Obituary.UserId;
           //}
               //db.Entry(events).State = EntityState.Modified;
                var currentEvent = db.Events.Find(events.EventId);
                events.UserProfile_UserId = WebSecurity.CurrentUserId;
                db.Entry(currentEvent).CurrentValues.SetValues(events);

                db.SaveChanges();

                var data = new
                {
                    name = events.EventName,
                    info = events.EventInfo,
                    venue = events.EventVenue,
                    date = events.EventDate,
                    duration = events.ApprximateDuration
                };
                //return RedirectToAction("Details",new RouteValueDictionary(new{contriller = "Event",id=events.EventId,message="Event Updarted!"}));
                return Json(data);
              
                //context..Attach(obj);
                ////context.ObjectStateManager.ChangeObjectState(obj, EntityState.Modified);
                ////context.tableentityname.ApplyCurrentValues(obj)
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }

        // GET: /Post/Details/5
        [Authorize]
        public ActionResult Details(int id,string message)
        {
            Events events = db.Events.Find(id);
            if (!string.IsNullOrEmpty(message))
            {
                ViewBag.message = message;
            }
            if (events == null)
            {
                return HttpNotFound();
            }
            // Comment co= db.Comments.Where(c => c.ObituaryId == id).ToList();
            //ViewBag.comment = co;
            var post = db.Obituary.Where(c => c.ObituaryId == events.ObituaryId).SingleOrDefault();
            ViewBag.post = post.Classifications;
            return View(events);
        }

        //
        // GET: /Post/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Events events = db.Events.Find(id);
            if (events == null)
            {
                return HttpNotFound();
            }
            return View(events);
        }

        //
        // POST: /Post/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Events events = db.Events.Find(id);
            if (events != null)
            {
                db.Events.Remove(events);

                db.SaveChanges();
                return Json(events, JsonRequestBehavior.AllowGet);
            }
            return Json(db.Events.Count(), JsonRequestBehavior.AllowGet);
        }

        //[HttpGet]

        //public ActionResult GetCommentCount(Obituary obituary)
        //{
        //    var comm = db.Events.Where(c => c.ObituaryId == obituary.ObituaryId).ToList().Count();

        //    return Json(comm);
        //}
    }
}

PMT/Controllers/PostController.cs
using PMT.Filters;
using PMT.Models;
using PMT.Utility;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebMatrix.WebData;

namespace PMT.Controllers
{
    [InitializeSimpleMembership]
    public class PostController : AppController
    {
        private PMTContext db = new PMTContext();

        //
        // GET: /Post/
        [HttpGet]

        public ActionResult Details(int id = 0)
        {
            Obituary obituary = db.Obituary.Find(id);
            if (obituary == null)
            {
                return HttpNotFound();
            }

            //ViewBag.comment = co;
            return View(obituary);
        }

        //
        // GET: /Post/Create
        [Authorize]
        public ActionResult Create()
        {

            List<SelectListItem> li = new List<SelectListItem>();
            li.Add(new SelectListItem { Text = "Obituary", Value = "Obituary" });
            li.Add(new SelectListItem { Text = "Tribute", Value = "Tribute" });
            ViewBag.classifications = li;
            

            List<SelectListItem> lis = new List<SelectListItem>();
            lis.Add(new SelectListItem { Text = "Select", Value = "" });
            lis.Add(new SelectListItem { Text = "Adult", Value = "Adult" });
            lis.Add(new SelectListItem { Text = "Child", Value = "Child" });
           
            ViewData["ObituaryCategory"] = lis;

            return View();
        }

        //
        // POST: /Post/Create






        public ActionResult Obituary_List(string message)
        {
            if (!string.IsNullOrEmpty(message))
            {
                ViewBag.message = message;
            }
            var obituaries = db.Obituary.Where(x => x.Classifications=="Obituary");
            return View(obituaries);
        }


        public ActionResult Tribute_List(string message)
        {
            if (!string.IsNullOrEmpty(message))
            {
                ViewBag.message = message;
            }
            var tributes = db.Obituary.Where(x => x.Classifications == "Tribute");
            return View(tributes.ToList());
        }



        [HttpGet]
        public ActionResult Obituaries_Next(int lastObituary)   
        {
            List<Obituary> Obituaries = db.Obituary.OrderByDescending(a => a.ObituaryId).ToList();
            int last = 0;
            if (lastObituary == -1)
            {
                Obituaries = Obituaries.Take(6).ToList();
            }
            else if (lastObituary > 0)
            {
                Obituary obituaries = new Obituary();
                obituaries = Obituaries.Where(d => d.ObituaryId == lastObituary).SingleOrDefault();
                if (obituaries != null)
                {
                    int p = Obituaries.IndexOf(obituaries);
                    Obituaries = Obituaries.Skip(p + 1).Take(5).ToList();
                }
            }
            else if (lastObituary == 0)
            {
                Obituaries = null;
            }
            if (Obituaries.Count > 0 && Obituaries != null)
            {
                int len = Obituaries.Count;
                last = Obituaries.ElementAt(len - 1).ObituaryId;
            }

            ViewBag.Obituaries = Obituaries;
            ViewBag.lastObituary = last;
            return PartialView("_Obituary_List");
        }






        [HttpPost]
        public ActionResult Create(Obituary obituary, HttpPostedFileBase imageFile)
        {
            obituary.UserId = (int)WebSecurity.CurrentUserId;
            
                List<SelectListItem> li = new List<SelectListItem>();
                li.Add(new SelectListItem { Text = "Obituary", Value = "Obituary" });
                li.Add(new SelectListItem { Text = "Tribute", Value = "Tribute" });
                ViewBag.classifications = li;


                List<SelectListItem> lis = new List<SelectListItem>();
                lis.Add(new SelectListItem { Text = "Select", Value = "" });
                lis.Add(new SelectListItem { Text = "Adult", Value = "Adult" });
                lis.Add(new SelectListItem { Text = "Child", Value = "Child" });

                ViewData["ObituaryCategory"] = lis;

                var imageName = "";

                imageName = imageFile.FileName;
                var httpPostedFile = Request.Files[0];
                if (httpPostedFile != null)
                {
                    var uploadFilesDir = System.Web.HttpContext.Current.Server.MapPath("~/Images/obituary");
                    if (!Directory.Exists(uploadFilesDir))
                    {
                        Directory.CreateDirectory(uploadFilesDir);
                    }
                    var fileSavePath = Path.Combine(uploadFilesDir, httpPostedFile.FileName);

                    httpPostedFile.SaveAs(fileSavePath);
                    obituary.FileName = imageName;
                }

                if (ModelState.IsValid)
                {
                    
                    db.Obituary.Add(obituary);
                    db.SaveChanges();
                    return RedirectToAction("Index", "Home", new { message = obituary.Classifications + " " + "Added Successfully" });

                    ViewBag.UserId = new SelectList(db.UserProfiles, "UserId", "UserName", obituary.UserId);
                }
            return View(obituary);
        }
            
        //
        // GET: /Post/Edit/5
    [Authorize]
        public ActionResult Edit(int id = 0)
        {


            List<SelectListItem> li = new List<SelectListItem>();
            li.Add(new SelectListItem { Text = "Obituary", Value = "Obituary" });
            li.Add(new SelectListItem { Text = "Tribute", Value = "Tribute" });

            ViewBag.classifications = li;
           


            List<SelectListItem> lis = new List<SelectListItem>();
            lis.Add(new SelectListItem { Text = "Select", Value = "" });
            lis.Add(new SelectListItem { Text = "Adult", Value = "Adult" });
            lis.Add(new SelectListItem { Text = "Child", Value = "Child" });
            ViewData["ObituaryCategory"] = lis;


            Obituary obituary = db.Obituary.Find(id);
            if (obituary == null)
            {
                return HttpNotFound();
            }

            return View(obituary);
        }

        //
        // POST: /Post/Edit/5

  [HttpPost]
        public ActionResult Edit(Obituary obituary, HttpPostedFileBase imageFile)
        {

            obituary.UserId = (int)WebSecurity.CurrentUserId;

            if (ModelState.IsValid)
            {


                var imageName = "";
                if (imageFile != null)
                {
                    imageName = imageFile.FileName;
                    var httpPostedFile = Request.Files[0];
                    if (httpPostedFile != null)
                    {
                        var uploadFilesDir = System.Web.HttpContext.Current.Server.MapPath("~/Images/obituary");
                        if (!Directory.Exists(uploadFilesDir))
                        {
                            Directory.CreateDirectory(uploadFilesDir);
                        }
                        var fileSavePath = Path.Combine(uploadFilesDir, httpPostedFile.FileName);

                        httpPostedFile.SaveAs(fileSavePath);
                        obituary.FileName = imageName;
                    }
                }
                //db.Entry(obituary).State = EntityState.Modified;
                var currentPost=db.Obituary.Find(obituary.ObituaryId);

                db.Entry(currentPost).CurrentValues.SetValues(obituary);
                db.SaveChanges();
                if(obituary.Classifications=="Obituary")
                {
                    return RedirectToAction("Obituary_List", new { message = obituary.Classifications + " " + "Updated Successfully" });
                }
                else if (obituary.Classifications == "Tribute")
                {
                    return RedirectToAction("Tribute_List", new { message = obituary.Classifications + " " + "Updated Successfully" });
                }
                
            }
            ViewBag.UserId = new SelectList(db.UserProfiles, "UserId", "UserName", obituary.UserId);
            return View(obituary);
        }

        //
        // GET: /Post/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Obituary obituary = db.Obituary.Find(id);
            if (obituary == null)
            {
                return HttpNotFound();
            }
            return View(obituary);
        }

        //
        // POST: /Post/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Obituary obituary = db.Obituary.Find(id);
            db.Obituary.Remove(obituary);
            db.SaveChanges();
            return RedirectToAction("Obituary_List");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

PMT/Controllers/SendMailerController.cs
using PMT.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;

namespace PMT.Controllers
{
    public class SendMailerController : Controller
    {
        //
        // GET: /SendMailer/

        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(MailModel _objModelMail)
        {
            PMTContext db = new PMTContext();
            db.SendMails.Add(_objModelMail);
            db.SaveChanges();
            //tHIS FOR GOOGLE-WORKING
            MailMessage mail = new MailMessage();
            mail.To.Add(_objModelMail.To);
            mail.From = new MailAddress(_objModelMail.From);
            mail.Subject = _objModelMail.Subject;
            string Body = _objModelMail.Body;
            mail.Body = Body;
            mail.IsBodyHtml = true;
           
            SmtpClient smtp = new SmtpClient();
            smtp.Host = "smtp.mandrillapp.com";
            smtp.Port = 587;
            smtp.UseDefaultCredentials = false;
            smtp.Credentials = new NetworkCredential("4a1992@gmail.com", "N5AMEOOPNKHZ846ZqDFZzw");
            smtp.EnableSsl = true;
            smtp.Send(mail);
            //return RedirectToAction("",null,new { message = "Mail Sent" });
            return RedirectToAction("Index","Home",new{ message = "Mail Sent Successfully"});
            //FOR yAHOOOOOO
            //MailMessage mail = new MailMessage();
            //mail.To.Add(_objModelMail.To);
            //mail.From = new MailAddress(_objModelMail.Email);
            //mail.Subject = _objModelMail.Subject;
            //string Body = _objModelMail.Body;
            //mail.Body = Body;
            //mail.IsBodyHtml = true;
            //SmtpClient smtp = new SmtpClient("plus.smtp.mail.yahoo.com");

            //smtp.Credentials = new NetworkCredential(_objModelMail.Email, _objModelMail.Password);
            //smtp.EnableSsl = true;
            //smtp.Port = 465;
            //smtp.UseDefaultCredentials = true;
            //smtp.Send(mail);
            //return View("Index", _objModelMail);
        }

        public ActionResult Send()
        {
            return View();
        }
    }
}

PMT/Views/Event/Delete.cshtml
@model PMT.Models.Events

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>
<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>Obituary</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.EventInfo)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.EventVenue)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.EventStartTime)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.EventEndTime)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ApprximateDuration)
    </div>
  
</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input  value="Delete"  id="deleteEvent" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

PMT/Views/Event/Details.cshtml
@model PMT.Models.Events

@{
    ViewBag.Title = "Details";
                        //var label = 
}
<style>
    .size {
        font-size: 22px;
    }

    div.right-align .facebook span {
        vertical-align: initial !important;
    }

    .twitter {
        margin-top: 10px;
    }

    .mtop10 {
        margin-top: 10px !important;
    }

    #mail {
        vertical-align: super;
        padding-left: 1px;
        font-size: 12px;
    }

    table#personDetails td {
        padding: 0px !important;
    }

    html {
        height: 100%;
    }

    body {
        height: 100%;
        margin: 0px;
        padding: 0px;
    }

    .gmap {
        width: 100%;
        height: 200px;
        border: 1px solid lightgray;
    }
</style>
<div class="container">
    <div class="row">
        <div class="col s12 event">
            <div class="col s12 right-align mtop10">

                <div id="socialLinks" class="right mbottom5">
                    <div class="fb-share-button facebook" data-href="http://localhost:1114" data-layout="button"></div>
                    <a href="https://twitter.com/share" class="twitter-share-button twitter" data-via="antariksha1703">Tweet</a>

                    @*<a target="_blank" href="https://plus.google.com/share?url=http://localhost:1114" class="social googleplus"></a>*@
                    <div class="g-plus" data-action="share" data-annotation="none" data-height="15px" data-href="http://localhost:1114"></div>
                    <i class="material-icons cyan-text">email</i>@Html.ActionLink("Mail", "Index", "SendMailer", new { id = "" }, new { @class = "modal-trigger black-text", @href = "#ObituarySend", @id = "mail" })
                </div>
            </div>
            <div class="row">
                <div class="col s12">
                   @* <div class="col s2 eventname_@Model.EventId" style="font-size: 2em;">@Html.DisplayFor(model => model.EventName)</div>
                    <div class="col s3 eventdate_@Model.EventId" style="font-size: 2em;">@Html.DisplayFor(model => model.EventDate)</div>*@

                    <h4 class="eventname_@Model.EventId">@Html.DisplayFor(model => model.EventName) on @Html.DisplayFor(model => model.EventDate)</h4>
                </div>
            </div>
            <div id="modal2" class="modal">
                <div class="modal-content">
                    <h6 class="center-align">Send Mails</h6>
                    @Html.Partial("~/Views/SendMailer/_IndexSendmail.cshtml")
                </div>
                <div class="modal-footer">
                    <a href="#!" id="close" class=" modal-action modal-close waves-effect waves-green btn-flat">Cancel</a>
                </div>
            </div>
            <div class="row">
                <div class="col s12">
                    @*<h6><strong>Venue:</strong> &nbsp; @Html.DisplayFor(model => model.EventVenue)</h6>
                <br />
                <h6><strong>Duration:</strong> &nbsp; @Html.DisplayFor(model => model.ApprximateDuration)</h6>*@

                    <h6><strong>Venue:</strong> &nbsp;
                            <span id="venue" class="eventvenue_@Model.EventVenue">@Html.DisplayFor(model => model.EventVenue)</span>
                    </h6>
                    <br />
                    <h6><strong>Duration:</strong> &nbsp;
                          <span class="duration_@Model.ApprximateDuration">@Html.DisplayFor(model => model.ApprximateDuration) hrs/mins </span></h6>


                </div>
            </div>
            </>

        @*<div>
            @Maps.GetGoogleHtml(Request.Form["@Html.DisplayFor(model => model.EventVenue)"],
            width: "400",
            height: "400"
            )
        </div>*@
            <input type="hidden" id="message" value="@ViewBag.message" />

            <div class="row">
                <div class="col s12">
                    <div id="map_canvas" class="gmap"></div>
                </div>
            </div>


            <div class="row">
                <div class="col s12 eventinfo_@Model.EventId">
                    <p>@Html.DisplayFor(model => model.EventInfo)</p>
                </div>

            </div>

            <div id="@Model.EventId"></div>
            @*<iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d15074.933762846144!2d72.94009643465577!3d19.163141996054993!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3bddd290b09914b3%3A0xcb07845d9d28215c!2sNashik%2C+Maharashtra!5e0!3m2!1sen!2sin!4v1449581468245" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>*@

            <div class="row">
                <div class="s12">
                    <ul style="list-style-type: none; float: right;">
                        <li style="display: inline;">@*@Html.ActionLink("Edit", "Edit", "Event", new { id = Model.EventId }, new { @class = "edit indigo-text" })*@
                            <a data-eventId="@Model.EventId" class="editevent indigo-text" style="cursor:pointer">Edit</a>
                        </li>
                        |
			    <li style="display: inline;">@Html.ActionLink("Back to " + (string)@ViewBag.post, "Details", "Post", new { id = Model.ObituaryId }, new { @class = "delete red-text" })</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>




    <script>
        $('.modal-trigger').leanModal();
    </script>
    <script type="text/javascript"
        src="http://maps.google.com/maps/api/js?v=3&key=AIzaSyAxedoISuyJYgaELGqTf2o1He6z6qsEWRI&sensor=true"></script>
    @*maps.googleapis.com/maps/api/js?v=3&key={your key}&sensor=false*@

    <script>
        function initialize() {

            // var latitude = 30.3296604;
            //var longitude = -97.8743174;
            //var geocoder = new google.maps.Geocoder();
            //var address = document.getElementById("venue").value;
            //geocoder.geocode({ 'address': address }, function (result) {
            //    debugger;

            //    var latitude = result.geometry.loca
            //        var longitude = result[0].geometry.location.lng();
            //        alert(latitude + longitude);



            var geocoder = new google.maps.Geocoder();
            var address = $("#venue").text();

            geocoder.geocode({ 'address': address }, function (results, status) {

                if (status == google.maps.GeocoderStatus.OK) {
                    var latitude = results[0].geometry.location.lat();
                    var longitude = results[0].geometry.location.lng();

                    var latlng = new google.maps.LatLng(latitude, longitude);
                    var options = {
                        zoom: 8,
                        center: latlng,
                        mapTypeId: google.maps.MapTypeId.ROADMAP
                    };
                    var map = new google.maps.Map(document.getElementById("map_canvas"), options);

                    var marker = new google.maps.Marker({
                        position: new google.maps.LatLng(latitude, longitude),
                        map: map
                    })
                }
            });
        }

        $(function () { //Same as $(document).ready()
            initialize();
        });


        $(document).ready(function () {
            toastr.options = {
                "closeButton": false,
                "debug": false,
                "positionClass": "toast-top-full-width",
                "onclick": null,
                "showDuration": "200",
                "hideDuration": "1500",
                "timeOut": "6000",
                "extendedTimeOut": "1200",
                "showEasing": "swing",
                "hideEasing": "linear",
                "showMethod": "fadeIn",
                "hideMethod": "fadeOut"

            }
            if ($('#message').val() != "")
                toastr["success"]($('#message').val());
        });

        $(document).on('click', '.editevent', function () {
            var commId = $(this).attr("data-eventId");
            alert(commId);
            $.ajax({
                url: "/Event/Edit",
                type: 'GET',
                data: { id: commId },
                success: function (data) {
                    $("#" + commId).append(data.PartialView);
                }
            })
        })
        $(document).on('click', '#cncelcomm', function () {
            var commId = $(this).attr("data-eventId");
            $("#" + commId).html("");

        })
        $(document).on('click', '.updateEvent', function () {
            var commId = $(this).attr("data-eventId");
            var form = $(".EditEventForm").serialize();
            alert(form);
            $.ajax({
                url: "/Event/Edit",
                type: 'POST',
                data: form,
              
                success: function (data) {
                    alert(data.date);
                    //$("." + commId).text(data.comment);
                    $(".eventname_" + commId).text(data.name+" on "+data.date);
                    $(".eventinfo_" + commId).text(data.info);
                    $(".eventvenue_" + commId).text(data.venue);
                    $(".duration_" + commId).text(data.duration);
                    $("#" + commId).html("");
                    
                }
            });

        });


    </script>

PMT/Views/Event/_Index.cshtml
@model IEnumerable<PMT.Models.Events>
@{
    //var id =
}

@*    <table class="highlight">
     <thead>
     <tr>
        
             <th>
            @Html.DisplayNameFor(model=>model.EventInfo)
        </th>
   
        
        </tr>
               </thead>
      
   @foreach (var item in Model)
   {
       <tbody>
           <tr>
        <td>
            @Html.DisplayFor(model => item.EventInfo)
        </td>
        
        <td class="right">
            @Html.ActionLink("Edit", "Edit", "Event", new { id = item.EventId }, htmlAttributes: new { @class="red-text"}) |
            @Html.ActionLink("Details", "Details", "Event", new { id = item.EventId },htmlAttributes: new { @class="red-indigo"})|
        @Html.ActionLink("Delete", "Delete", "Event", new { id = item.EventId }, new { @class="deleteEvent"})
        </td>
    </tr>   
       </tbody>
   
   }
</table>*@


@foreach (var item in Model)
{
    <div class="col s12" id="deleteevent_@item.EventId">
        <ul style="list-style-type: none; padding: 7px;" class="collection" >
            <li class="collection-header" >
                <h6>@Html.ActionLink(item.EventName, "Details", "Event", new { id = item.EventId }, htmlAttributes: new { @class = "black-text" }) (@Html.DisplayFor(m => item.EventDate))  <span class="deleteEvent red-text " style="float:right;cursor:pointer;" data-deleteeventidid="@item.EventId" >Delete</span></h6>
            </li>
        </ul>
    </div>
   
}



<script>
    $(document).off('click', '.deleteEvent').on('click', '.deleteEvent', function (e) {
        var commId = $(this).attr("data-deleteeventidid");
        alert(commId);
        $.ajax({
            url: "/Event/Delete",
            type: 'POST',
            data: { id: commId },
            success: function (data) {
                $("#deleteevent_" + commId).html('');
                var count = $("#PostEvntCount").text();
                count = parseInt(count) - 1;

                $("#PostEvntCount").text(count);
                $("#PostEvntCount").val(count);
            }
        })

    })

</script>